/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public\models\creep.glb
Author: ArachnoBoy (https://sketchfab.com/vang807)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/arachnoseeker-c194bb09ab064109a009027f29eaf614
Title: Arachnoseeker
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Creep(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/public/models/creep.glb')
  const { actions,names } = useAnimations(animations, group)

  useEffect(() => {
    // Log available animations to the console
    console.log('Available animations:', names);

    // Example: Play the first animation
    if (names.length > 0) {
      actions[names[0]].play();
    }
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sketchfab_model_0" rotation={[-Math.PI / 2, 0, 0]}>
                <group name="root_1">
                  <group name="GLTF_SceneRootNode_2" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="GLTF_created_0_3">
                      <group name="GLTF_created_0">
                        <primitive object={nodes.GLTF_created_0_rootJoint} />
                        <group name="Object_7_7_correction">
                          <group name="Object_7_7" />
                        </group>
                        <skinnedMesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.BatraBeholder_001_MI} skeleton={nodes.Object_33.skeleton} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/public/models/creep.glb')
