/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public\models\pig.glb
Author: NO DONT EAT ME CASEOH (Ferris wheel) (https://sketchfab.com/NO.DONT.EAT.ME.CASEOH)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/piggy-the-hunt-scry-rig-c46d8df6b9e344c2895b3d53013dd3a9
Title: Piggy The Hunt Scry Rig
*/

import React, { useRef ,useEffect} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Pig(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/public/models/pig.glb')
  const { actions ,names } = useAnimations(animations, group)

  useEffect(() => {
    // Log available animations to the console
    console.log('Available animations:', names);

    // Example: Play the first animation
    if (names.length > 0) {
      actions[names[0]].play();
    }
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 4]} scale={0.1}>
          <group name="2b742d47405a44b2b6e889883dd0bab9fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Scry" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Scry_skeleton" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_8" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Whiteglow} skeleton={nodes.Object_9.skeleton} />
                    <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Eyemain1Mtl} skeleton={nodes.Object_10.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/public/models/pig.glb')
