/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public\models\threehead.glb
Author: chatholoboom7745289 (https://sketchfab.com/chabsfabo86)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/chimera-final-fantasy-x-24807b6633cb4aa38ec4b7ac17088972
Title: Chimera - Final Fantasy X
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function ThreeHead(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/public/models/threehead.glb')
  const { actions ,names} = useAnimations(animations, group)

  useEffect(() => {
    // Log available animations to the console
    console.log('Available animations:', names);

    // Example: Play the first animation
    if (names.length > 0) {
      actions[names[0]].play();
    }
  }, [actions, names]);


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[Math.PI / 2, 0, 3]} scale={900}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="bone000_138" position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="0000_object00_131" />
                  <group name="0001_object00_132" />
                  <group name="0002_object00_133" />
                  <group name="0003_object01_134" />
                  <group name="0004_object02_135" />
                  <group name="0005_object03_136" />
                  <group name="0006_object04_137" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.mat000} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.mat001} skeleton={nodes.Object_9.skeleton} />
                  <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.mat002} skeleton={nodes.Object_11.skeleton} />
                  <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.mat001} skeleton={nodes.Object_13.skeleton} />
                  <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.mat002} skeleton={nodes.Object_15.skeleton} />
                  <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.mat002} skeleton={nodes.Object_17.skeleton} />
                  <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.mat000} skeleton={nodes.Object_19.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/public/models/threehead.glb')
